/* eslint-disable @next/next/no-img-element -- The QR is generated by an authenticated same-origin endpoint. */
import Link from "next/link";
import { eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { getDb } from "@/db";
import { companies, motorcycles, transportJobs } from "@/db/schema";
import { can } from "@/lib/authorization";
import { requireActor } from "@/lib/current-actor";

export const dynamic = "force-dynamic";

export default async function MotorcycleLabelPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const actor = await requireActor(`/app/motorcycles/${id}/label`);
  const record = await getDb()
    .select({
      id: motorcycles.id,
      publicId: motorcycles.publicId,
      companyId: motorcycles.companyId,
      companyName: companies.displayName,
      jobNumber: transportJobs.jobNumber,
      sequenceNumber: motorcycles.sequenceNumber,
      make: motorcycles.make,
      model: motorcycles.model,
      color: motorcycles.color,
      registration: motorcycles.registration,
    })
    .from(motorcycles)
    .innerJoin(companies, eq(companies.id, motorcycles.companyId))
    .innerJoin(transportJobs, eq(transportJobs.id, motorcycles.jobId))
    .where(eq(motorcycles.id, id))
    .get();
  if (!record || !can(actor, "motorcycles:write", record.companyId)) notFound();

  return (
    <>
      <div className="app-page-head print-hidden">
        <div><p>SECURE VEHICLE LABEL</p><h1>ฉลาก QR รถคันที่ {record.sequenceNumber}</h1><span>QR ไม่บรรจุทะเบียน VIN หรือข้อมูลลูกค้า</span></div>
        <div className="app-page-actions"><Link href={`/app/motorcycles/${record.id}`}>← กลับรายละเอียด</Link><PrintButton label="พิมพ์ฉลาก" /></div>
      </div>
      <div className="label-sheet single-label-sheet">
        <VehicleLabel record={record} />
      </div>
    </>
  );
}

function VehicleLabel({ record }: { record: {
  publicId: string;
  companyName: string;
  jobNumber: string;
  sequenceNumber: number;
  make: string | null;
  model: string | null;
  color: string | null;
  registration: string | null;
} }) {
  return (
    <article className="vehicle-label">
      <div className="vehicle-label-brand"><b>NATHEE GROUP 2025</b><span>SECURE TRANSPORT LABEL</span></div>
      <img src={`/api/qr/motorcycles/${encodeURIComponent(record.publicId)}`} alt={`QR สำหรับรถคันที่ ${record.sequenceNumber}`} width={232} height={232} decoding="sync" />
      <div className="vehicle-label-copy">
        <h2>{record.jobNumber} · #{record.sequenceNumber}</h2>
        <p>{record.companyName}</p>
        <dl>
          <div><dt>รถ</dt><dd>{[record.make, record.model].filter(Boolean).join(" ") || "ไม่ระบุ"}</dd></div>
          <div><dt>สี</dt><dd>{record.color || "—"}</dd></div>
          <div><dt>ทะเบียน</dt><dd>{record.registration || "—"}</dd></div>
        </dl>
        <small>{record.publicId}</small>
      </div>
    </article>
  );
}
