export type RuntimeChecks = {
  authentication: boolean;
  adminAuthentication: boolean;
  canonicalOrigin: boolean;
  database: boolean;
  storage: boolean;
  antiAbuse: boolean;
};

/**
 * Everything the migrations create, and therefore everything "the schema is
 * applied" means.
 *
 * This list used to be curated by hand, and it had drifted: 48 of the 81 safety
 * triggers were absent from it, including the ones that keep a last active OWNER
 * from being removed and the ones that keep a role and a company scope
 * compatible. A runtime missing those enforces none of them and still reported
 * `healthy`, because nothing was looking for them. Triggers are the objects that
 * fail silently — the application keeps working and the invariant is simply gone.
 *
 * `scripts/test-readiness-contract.mjs` now derives the same three sets from the
 * migrations and fails the build on any difference, so the list cannot drift
 * again in either direction.
 */
export const REQUIRED_TABLES = [
  "audit_logs",
  "auth_attempt_counters",
  "auth_recovery_grants",
  "companies",
  "container_motorcycle_assignments",
  "container_status_events",
  "gallery_categories",
  "gallery_image_variants",
  "gallery_items",
  "inspection_findings",
  "motorcycle_image_variants",
  "motorcycle_images",
  "motorcycle_import_batches",
  "motorcycle_import_rows",
  "motorcycle_inspections",
  "motorcycles",
  "notifications",
  "post_publication_events",
  "post_revisions",
  "posts",
  "proof_of_delivery_records",
  "proof_of_delivery_signatures",
  "quote_request_attachments",
  "quote_requests",
  "sequence_counters",
  "shipping_containers",
  "site_page_publication_events",
  "site_page_revisions",
  "site_pages",
  "site_settings_publication_events",
  "site_settings_revisions",
  "status_events",
  "transport_jobs",
  "trip_motorcycle_assignments",
  "trip_status_events",
  "trips",
  "trucks",
  "user_permissions",
  "user_role_assignments",
  "users",
  "yard_placements",
  "yard_rows",
  "yard_slots",
  "yard_zones",
] as const;

export const REQUIRED_TRIGGERS = [
  "trg_audit_logs_no_delete",
  "trg_audit_logs_no_update",
  "trg_container_assignments_identity_immutable",
  "trg_container_assignments_no_delete",
  "trg_container_assignments_validate_insert",
  "trg_container_assignments_validate_state",
  "trg_container_events_no_delete",
  "trg_container_events_no_update",
  "trg_inspection_findings_no_delete",
  "trg_inspection_findings_no_update",
  "trg_inspection_findings_validate_insert",
  "trg_motorcycle_image_variants_immutable",
  "trg_motorcycle_image_variants_no_delete",
  "trg_motorcycle_images_immutable",
  "trg_motorcycle_images_no_delete",
  "trg_motorcycle_import_batches_identity_immutable",
  "trg_motorcycle_import_batches_no_delete",
  "trg_motorcycle_import_batches_transition",
  "trg_motorcycle_import_rows_identity_immutable",
  "trg_motorcycle_import_rows_no_delete",
  "trg_motorcycle_import_rows_transition",
  "trg_motorcycle_inspections_no_delete",
  "trg_motorcycle_inspections_no_update",
  "trg_motorcycle_inspections_validate_insert",
  "trg_motorcycles_require_active_pod",
  "trg_motorcycles_require_new_pod_signature",
  "trg_motorcycles_require_receipt_inspection",
  "trg_pod_records_identity_immutable",
  "trg_pod_records_no_delete",
  "trg_pod_records_require_signature_flag_insert",
  "trg_pod_records_signature_required_immutable",
  "trg_pod_records_validate_insert",
  "trg_pod_records_validate_void",
  "trg_pod_signatures_no_delete",
  "trg_pod_signatures_no_update",
  "trg_pod_signatures_validate_insert",
  "trg_post_publication_revision_scope",
  "trg_post_publications_immutable_update",
  "trg_post_publications_no_delete",
  "trg_post_revisions_immutable_update",
  "trg_post_revisions_no_delete",
  "trg_quote_request_attachments_immutable",
  "trg_quote_request_attachments_no_delete",
  "trg_quote_requests_identity_immutable",
  "trg_quote_requests_no_delete",
  "trg_quote_requests_public_requirements",
  "trg_shipping_containers_identity_immutable",
  "trg_shipping_containers_no_delete",
  "trg_shipping_containers_plan_fields_locked",
  "trg_shipping_containers_seal_locked",
  "trg_shipping_containers_validate_status",
  "trg_site_home_cannot_hide",
  "trg_site_page_publication_revision_scope",
  "trg_site_page_publications_immutable_update",
  "trg_site_page_publications_no_delete",
  "trg_site_page_revisions_immutable_update",
  "trg_site_page_revisions_no_delete",
  "trg_site_pages_identity_immutable",
  "trg_site_pages_no_delete",
  "trg_site_settings_publications_immutable_update",
  "trg_site_settings_publications_no_delete",
  "trg_site_settings_revisions_immutable_update",
  "trg_site_settings_revisions_no_delete",
  "trg_transport_jobs_public_id_immutable",
  "trg_transport_jobs_public_id_insert",
  "trg_trip_assignments_identity_immutable",
  "trg_trip_assignments_no_active_container",
  "trg_trip_assignments_no_delete",
  "trg_trip_assignments_validate_insert",
  "trg_trip_assignments_validate_state",
  "trg_trips_driver_single_commitment_insert",
  "trg_trips_driver_single_commitment_update",
  "trg_trips_public_id_immutable",
  "trg_trips_public_id_insert",
  "trg_trips_truck_single_commitment_insert",
  "trg_trips_truck_single_commitment_update",
  "trg_trips_validate_resources_insert",
  "trg_trips_validate_resources_update",
  "trg_trips_validate_status_transition",
  "trg_trucks_public_id_immutable",
  "trg_trucks_public_id_insert",
  "trg_user_role_assignments_compatible_insert",
  "trg_user_role_assignments_compatible_update",
  "trg_user_roles_keep_last_active_owner_delete",
  "trg_user_roles_keep_last_active_owner_update",
  "trg_users_keep_last_active_owner_legacy_role",
  "trg_users_keep_last_active_owner_status",
  "trg_users_role_assignment_compatible_update",
  "trg_yard_placements_company_scope",
  "trg_yard_placements_history_immutable",
  "trg_yard_placements_require_slot_when_mapped",
  "trg_yard_placements_row_belongs_to_zone",
  "trg_yard_placements_slot_belongs_to_zone",
  "trg_yard_placements_slot_usable",
  "trg_yard_placements_zone_active",
  "trg_yard_placements_zone_capacity",
  "trg_yard_slots_zone_capacity_conflict",
  "trg_yard_zones_capacity_when_slotted",
  "trg_yard_zones_public_id_immutable",
  "trg_yard_zones_public_id_insert",
] as const;

export const REQUIRED_INDEXES = [
  "idx_audit_logs_action_created",
  "idx_audit_logs_company_created",
  "idx_audit_logs_created_id",
  "idx_audit_logs_entity_created",
  "idx_auth_attempt_counters_updated",
  "idx_auth_recovery_grants_expires",
  "idx_auth_recovery_grants_identity",
  "idx_companies_display_name_code",
  "idx_companies_status",
  "idx_companies_status_code",
  "idx_companies_status_display_name_code",
  "idx_container_assignments_company_active",
  "idx_container_assignments_container_state",
  "idx_container_status_events_container_created",
  "idx_gallery_categories_status_sort",
  "idx_gallery_image_variants_item_role",
  "idx_gallery_items_category_order",
  "idx_gallery_items_company_job",
  "idx_gallery_items_public_order",
  "idx_inspection_findings_evidence",
  "idx_inspection_findings_inspection_created",
  "idx_motorcycle_image_variants_image_role",
  "idx_motorcycle_images_company",
  "idx_motorcycle_images_motorcycle_created",
  "idx_motorcycle_import_batches_company_created",
  "idx_motorcycle_import_batches_job_created",
  "idx_motorcycle_import_rows_batch_status_row",
  "idx_motorcycle_inspections_company_at",
  "idx_motorcycle_inspections_motorcycle_type_at",
  "idx_motorcycles_company_status",
  "idx_motorcycles_job",
  "idx_motorcycles_registration",
  "idx_notifications_recipient_created",
  "idx_notifications_recipient_unread",
  "idx_notifications_source_event",
  "idx_pod_records_company_delivered",
  "idx_pod_records_motorcycle_created",
  "idx_pod_signatures_company_created",
  "idx_post_publication_post_created",
  "idx_post_publication_revision",
  "idx_post_revisions_post_created",
  "idx_posts_updated",
  "idx_quote_request_attachments_quote_created",
  "idx_quote_requests_status_created",
  "idx_shipping_containers_status_created",
  "idx_site_page_publication_page_created",
  "idx_site_page_publication_revision",
  "idx_site_page_revisions_page_created",
  "idx_site_pages_updated",
  "idx_site_settings_publication_created",
  "idx_site_settings_publication_revision",
  "idx_site_settings_revisions_created",
  "idx_status_events_company_created",
  "idx_status_events_motorcycle_created",
  "idx_transport_jobs_company_created",
  "idx_transport_jobs_company_created_id",
  "idx_transport_jobs_created_id",
  "idx_transport_jobs_status",
  "idx_trip_assignments_company_active",
  "idx_trip_assignments_trip_state",
  "idx_trip_status_events_trip_created",
  "idx_trips_driver_status",
  "idx_trips_status_planned",
  "idx_trips_truck_status",
  "idx_trucks_status_code",
  "idx_user_permissions_user",
  "idx_user_role_assignments_role",
  "idx_users_company_role",
  "idx_users_status",
  "idx_users_status_display_name_id",
  "idx_users_status_email_id",
  "idx_yard_placements_company_entered",
  "idx_yard_placements_motorcycle_entered",
  "idx_yard_placements_slot_entered",
  "idx_yard_placements_zone_active",
  "idx_yard_rows_zone_order",
  "idx_yard_slots_row_order",
  "idx_yard_zones_status_code",
  "uq_companies_code",
  "uq_container_assignments_motorcycle_active",
  "uq_container_assignments_request_key",
  "uq_gallery_categories_slug",
  "uq_gallery_image_variants_item_role_type",
  "uq_gallery_image_variants_storage_key",
  "uq_gallery_items_request_key",
  "uq_motorcycle_image_variants_image_role_type",
  "uq_motorcycle_image_variants_storage_key",
  "uq_motorcycle_images_request_key",
  "uq_motorcycle_images_storage_key",
  "uq_motorcycle_import_batches_import_request",
  "uq_motorcycle_import_batches_job_checksum",
  "uq_motorcycle_import_batches_request_key",
  "uq_motorcycle_import_rows_batch_row",
  "uq_motorcycle_import_rows_public_id",
  "uq_motorcycle_import_rows_record_id",
  "uq_motorcycle_inspections_request_key",
  "uq_motorcycles_engine_number",
  "uq_motorcycles_job_sequence",
  "uq_motorcycles_public_id",
  "uq_motorcycles_vin",
  "uq_notifications_idempotency_key",
  "uq_pod_records_motorcycle_active",
  "uq_pod_records_request_key",
  "uq_pod_signatures_pod",
  "uq_pod_signatures_storage_key",
  "uq_post_publication_request_key",
  "uq_post_revisions_request_key",
  "uq_posts_slug",
  "uq_quote_request_attachments_quote_checksum",
  "uq_quote_request_attachments_storage_key",
  "uq_quote_requests_request_key",
  "uq_quote_requests_request_number",
  "uq_shipping_containers_number",
  "uq_shipping_containers_public_id",
  "uq_shipping_containers_request_key",
  "uq_site_page_publication_request_key",
  "uq_site_page_revisions_request_key",
  "uq_site_pages_slug",
  "uq_site_settings_publication_request_key",
  "uq_site_settings_revisions_request_key",
  "uq_transport_jobs_job_number",
  "uq_transport_jobs_public_id",
  "uq_trip_assignments_motorcycle_active",
  "uq_trip_assignments_request_key",
  "uq_trips_public_id",
  "uq_trips_request_key",
  "uq_trips_trip_number",
  "uq_trucks_code",
  "uq_trucks_public_id",
  "uq_trucks_registration",
  "uq_trucks_request_key",
  "uq_users_email",
  "uq_users_external_auth_id",
  "uq_users_username",
  "uq_yard_placements_motorcycle_active",
  "uq_yard_placements_request_key",
  "uq_yard_placements_slot_active",
  "uq_yard_rows_zone_code",
  "uq_yard_slots_row_code",
  "uq_yard_zones_code",
  "uq_yard_zones_public_id",
] as const;

/** One flat contract for the probe, derived from the three sets above. */
export const REQUIRED_DATABASE_OBJECTS: ReadonlyArray<{ type: string; name: string }> = [
  ...REQUIRED_TABLES.map((name) => ({ type: "table", name })),
  ...REQUIRED_INDEXES.map((name) => ({ type: "index", name })),
  ...REQUIRED_TRIGGERS.map((name) => ({ type: "trigger", name })),
];

export function databaseObjectsReady(rows: ReadonlyArray<{ name: string; type: string }>): boolean {
  const found = new Set(rows.map((row) => `${row.type}:${row.name}`));
  return REQUIRED_DATABASE_OBJECTS.every((object) => found.has(`${object.type}:${object.name}`));
}

/**
 * What is missing, for an operator who has to fix it. The probe reports only a
 * boolean; this is for the deployment runbook and the tests.
 */
export function missingDatabaseObjects(
  rows: ReadonlyArray<{ name: string; type: string }>,
): ReadonlyArray<{ type: string; name: string }> {
  const found = new Set(rows.map((row) => `${row.type}:${row.name}`));
  return REQUIRED_DATABASE_OBJECTS.filter((object) => !found.has(`${object.type}:${object.name}`));
}

export function runtimeReadiness(checks: RuntimeChecks) {
  const healthy = Object.values(checks).every(Boolean);
  return {
    statusCode: healthy ? 200 : 503,
    payload: {
      status: healthy ? "healthy" as const : "degraded" as const,
      checks,
    },
  };
}
