/* eslint-disable @next/next/no-img-element -- The QR is generated by an authenticated same-origin endpoint. */
import Link from "next/link";
import { and, asc, eq, gt } from "drizzle-orm";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { getDb } from "@/db";
import { companies, motorcycles, transportJobs } from "@/db/schema";
import { can } from "@/lib/authorization";
import { requireActor } from "@/lib/current-actor";
import { LABEL_BATCH_SIZE, parseLabelCursor } from "@/lib/qr";

export const dynamic = "force-dynamic";

type JobLabelsProps = {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ after?: string }>;
};

export default async function JobLabelsPage({ params, searchParams }: JobLabelsProps) {
  const { id } = await params;
  const { after } = await searchParams;
  const cursor = parseLabelCursor(after);
  if (cursor === null) notFound();

  const actor = await requireActor(`/app/jobs/${id}/labels`);
  const db = getDb();
  const job = await db
    .select({
      id: transportJobs.id,
      jobNumber: transportJobs.jobNumber,
      companyId: transportJobs.companyId,
      companyName: companies.displayName,
      origin: transportJobs.origin,
      destination: transportJobs.destination,
    })
    .from(transportJobs)
    .innerJoin(companies, eq(companies.id, transportJobs.companyId))
    .where(eq(transportJobs.id, id))
    .get();
  if (!job || !can(actor, "motorcycles:write", job.companyId)) notFound();

  const rows = await db
    .select({
      publicId: motorcycles.publicId,
      sequenceNumber: motorcycles.sequenceNumber,
      make: motorcycles.make,
      model: motorcycles.model,
      color: motorcycles.color,
      registration: motorcycles.registration,
    })
    .from(motorcycles)
    .where(and(eq(motorcycles.jobId, id), gt(motorcycles.sequenceNumber, cursor)))
    .orderBy(asc(motorcycles.sequenceNumber))
    .limit(LABEL_BATCH_SIZE + 1)
    .all();
  const hasMore = rows.length > LABEL_BATCH_SIZE;
  const batch = rows.slice(0, LABEL_BATCH_SIZE);
  const nextCursor = batch.at(-1)?.sequenceNumber;

  return (
    <>
      <div className="app-page-head print-hidden">
        <div><p>BOUNDED BATCH PRINT</p><h1>ฉลากงาน {job.jobNumber}</h1><span>{job.companyName} · {job.origin} → {job.destination} · สูงสุด {LABEL_BATCH_SIZE} ฉลากต่อชุด</span></div>
        <div className="app-page-actions"><Link href="/app/jobs">← กลับงานขนส่ง</Link>{batch.length > 0 && <PrintButton />}</div>
      </div>

      {batch.length > 0 ? (
        <div className="label-sheet">
          {batch.map((record) => (
            <article className="vehicle-label" key={record.publicId}>
              <div className="vehicle-label-brand"><b>NATHEE GROUP 2025</b><span>SECURE TRANSPORT LABEL</span></div>
              <img src={`/api/qr/motorcycles/${encodeURIComponent(record.publicId)}`} alt={`QR สำหรับรถคันที่ ${record.sequenceNumber}`} />
              <div className="vehicle-label-copy">
                <h2>{job.jobNumber} · #{record.sequenceNumber}</h2>
                <p>{job.companyName}</p>
                <dl>
                  <div><dt>รถ</dt><dd>{[record.make, record.model].filter(Boolean).join(" ") || "ไม่ระบุ"}</dd></div>
                  <div><dt>สี</dt><dd>{record.color || "—"}</dd></div>
                  <div><dt>ทะเบียน</dt><dd>{record.registration || "—"}</dd></div>
                </dl>
                <small>{record.publicId}</small>
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="app-panel app-empty"><div>⌗</div><h2>ไม่มีฉลากในชุดนี้</h2><p>ตรวจลำดับชุดหรือเพิ่มรถในงานก่อนพิมพ์</p></div>
      )}

      <nav className="batch-navigation print-hidden" aria-label="ชุดฉลากถัดไป">
        <span>ชุดนี้: {batch.length} ฉลาก{cursor > 0 ? ` · หลังคันที่ ${cursor}` : ""}</span>
        {hasMore && nextCursor !== undefined && <Link className="button button-glass" href={`/app/jobs/${id}/labels?after=${nextCursor}`}>เปิดชุดถัดไป →</Link>}
        {!hasMore && batch.length > 0 && <span>ครบทุกฉลากแล้ว</span>}
      </nav>
    </>
  );
}
